### ISSUE TITLE
comparison with MATLAB quadprog

### ISSUE THREAD

**Issue by aghaeifar** [fnoorian/quadprogpp#5]
Hi 

I am trying to do a simple comparison with MATLAB [quadprog](https://uk.mathworks.com/help/optim/ug/quadprog.html) command where I get two different results.  
Do you have any idea why they may differ?

Wondering to know if the program solves 
0.5 * x G x + g0 x   (according to comments in eiquadprog.h)
or 
0.5 * x**T** G x + g0 x  (according to definitions of quadratic objective function)

Here is my simple test:

C++
```
G << 2.1, 0.0, 1.0,
	 1.5, 2.2, 0.0,
	 1.2, 1.3, 3.1;

g0 << 6, 1, 1;

CE << 0, 0, 0;

ce0(0) = 0;

CI << 1, 0, 0,
	 0, 1, 0,
	 0, 0, 1;

ci0 << 0, 0, 0;
```
Which gives: x =  -5.08475 ,  2.71186  , 0.508475
According to inequality constraint, all x elements must be positive! 

MATLAB
```
G = [2.1, 0.0, 1.0
		1.5, 2.2, 0.0
		1.2, 1.3, 3.1];
g0 = [6, 1, 1];


CI = [ -1, 0, 0
		0, -1, 0
		0, 0, -1];

ci0 = [0, 0, 0];

quadprog(G, g0, CI, ci0)
```

Which gives: x = 1.48e-14   ,   6.17e-12   ,   4.58e-11

**Comment by fnoorian** [comment]
I think it is because MATLAB is expecting a column-major data order, while C/C++ is row-major order.

So in this case, simply transpose the G and CI matrices:
```R
>>> G = matrix(c(2.1, 1.5, 1.2,
>>>              0.0, 2.2, 1.3,
>>>              1.0, 0.0, 3.1), 3, 3)
>>> 
>>> g0 = c(6.0, 1.0, 1.0)  
>>> 
>>> 
>>> CI = matrix(c( 1,  0,  0, 
>>>                0,  1,  0, 
>>>                0,  0,  1), 3, 3)
>>> 
>>> ci0 = c(0, 0, 0)
>>> 
>>> x = QP.Solve(G, g0, CI, ci0)
>>> print(x)
[1] -8.283596e-17 -6.305643e-17  0.000000e+00
```
which matches MATLAB's output.

Also, current project is for the R package. See https://github.com/liuq/QuadProgpp for the upstream C++ project.
